name: "Cartoomics"
channels:
  - conda-forge
  - anaconda
  - default
dependencies:
  - python==3.11.7
  - tqdm==4.66.1
  - gensim==4.3.2
  - numpy==1.26.3
  - scipy==1.12.0
  - pandas==2.1.4
  - pip
  - pip:
    - csrgraph==0.1.28
    - nodevectors==0.1.23
    - igraph==0.11.3
    - py4cytoscape==1.9.0
    - python-json-logger==2.0.7
    - matplotlib==3.8.2
    - seaborn==0.13.2
    - beautifulsoup4==4.12.3
    - bioservices==1.11.2
    - shapely==2.0.2
    - fiona==1.9.5
    - geopandas==0.14.2
    - unidecode==1.3.8
    - networkx==3.2.1

